<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function aov_builder_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Adding custom validation for the welcome page type field.
  if ($form['#form_id']== 'webform_submission_build_calculator_add_form') {
	$heroData = aov_builder_query_heroes();
	$itemData = aov_builder_query_items();
	$arcanaData = aov_builder_query_arcana();
	$skillAndBonusData = aov_builder_query_skills_and_bonuses();
	$form['#attached']['drupalSettings']['skillAndBonusData'] = $skillAndBonusData;
	$form['#attached']['drupalSettings']['arcanaData'] = $arcanaData;
	$form['#attached']['drupalSettings']['heroData'] = $heroData;
	$form['#attached']['drupalSettings']['itemData'] = $itemData;
	$form['#attached']['library'][] = 'aov_builder/build_calculator';
	return $form;
  }
}

function aov_builder_query_heroes() {
  $data = array();
  $heroKeys = array(
  "field_ability_power",
  "field_ad_per_level",
  "field_armor",
  "field_armor_per_level",
  "field_as_per_level",
  "field_attack_damage",
  "field_attack_speed",
  "field_cdr",
  "field_crit_chance",
  "field_critd_per_level",
  "field_critical_damage",
  "field_flat_pen_ad",
  "field_flat_pen_ap",
  "field_hp",
  "field_hp5_per_level",
  "field_hp_per_level",
  "field_hp_regen_5_seconds",
  "field_life_steal",
  "field_magic_defense",
  "field_magic_life_steal",
  "field_mana",
  "field_mana5_per_level",
  "field_mana_per_level",
  "field_mana_regen_5_seconds",
  "field_md_per_level",
  "field_movement_speed",
  "field_percent_pen_ad",
  "field_percent_pen_ap",
  );
  $query = \Drupal::entityQuery('node')
    ->condition('status', 1)
    ->condition('type', 'hero');
  $nids = $query->execute();
  $nodes = entity_load_multiple('node', $nids);
  foreach ($nodes as $node) {
	$nid = $node->id();
    foreach ($heroKeys as $key) {
	  $data[$nid][$key]['values'] = $node->get($key)->getValue();
	  $data[$nid][$key]['labels'] = $node->$key->getFieldDefinition()->getLabel();
	  $data[$nid]['title'] = $node->label();
    }
  }
  return $data;
}

function aov_builder_query_items() {
  $data = array();
  $itemKeys = array(
  "field_ability_power",
  "field_armor",
  "field_attack_damage",
  "field_attack_speed",
  "field_cdr",
  "field_crit_chance",
  "field_flat_pen_ad",
  "field_flat_pen_ap",
  "field_hp",
  "field_hp_regen_5_seconds",
  "field_life_steal",
  "field_magic_defense",
  "field_magic_life_steal",
  "field_mana",
  "field_mana_regen_5_seconds",
  "field_movement_speed",
  "field_percent_pen_ad",
  "field_percent_pen_ap",
  "field_passive_description",
  "field_cost",
  "field_movement_speed",
  "field_movement_speed_percent",
  );
  $query = \Drupal::entityQuery('node')
    ->condition('status', 1)
    ->condition('type', 'item');
  $nids = $query->execute();
  $nodes = entity_load_multiple('node', $nids);
  foreach ($nodes as $node) {
    $nid = $node->id();
	foreach ($itemKeys as $key) {
	  $data[$nid][$key] = $node->get($key)->getValue();
	}
  }
  return $data;
}

function aov_builder_query_arcana() {
  $data = array();
  $arcanaKeys = array(
  "field_ability_power",
  "field_armor",
  "field_attack_damage",
  "field_attack_speed",
  "field_cdr",
  "field_crit_chance",
  "field_critical_damage",
  "field_flat_pen_ad",
  "field_flat_pen_ap",
  "field_hp",
  "field_hp_regen_5_seconds",
  "field_life_steal",
  "field_magic_defense",
  "field_magic_life_steal",
  "field_movement_speed_percent",
  "field_cost",
  "field_gold_value",
  );
  $query = \Drupal::entityQuery('node')
    ->condition('status', 1)
    ->condition('type', 'arcana');
  $nids = $query->execute();
  $nodes = entity_load_multiple('node', $nids);
  foreach ($nodes as $node) {
    $nid = $node->id();
	foreach ($arcanaKeys as $key) {
	  $data[$nid][$key]['values'] = $node->get($key)->getValue();
	}
  }
  return $data;
}

function aov_builder_query_skills_and_bonuses() {
  $data = array();
  //get skills
  $skillKeys = array(
  "body",
  "field_hero",
  "field_cooldown",
  "field_cooldown_per_level",
  "field_output_type",
  "field_scaling",
  "field_scaling_stat",
  "field_skill_cost",
  "field_skill_type",
  "field_level_1",
  "field_skill_damage_per_level",
  );
  $skillQuery = \Drupal::entityQuery('node')
    ->condition('status', 1)
    ->condition('type', 'skill');
  $skillNids = $skillQuery->execute();
  $skillNodes = entity_load_multiple('node', $skillNids);
  //get bonuses
  $bonusKeys = array(
  "body",
  "field_bonus_damage_level_1",
  "field_bonus_damage_per_level",
  "field_damage_over_time",
  "field_output_type",
  "field_scaling",
  "field_scaling_stat",
  "field_skill_reference",
  );
  $bonusQuery = \Drupal::entityQuery('node')
    ->condition('status', 1)
    ->condition('type', 'bonus');
  $bonusNids = $bonusQuery->execute();
  $bonusNodes = entity_load_multiple('node', $bonusNids);
  //assemble data keyed by hero, then skill, then bonuses
  foreach ($skillNodes as $node) {
	$heroID = $node->get('field_hero')->getValue()['target_id'];
	$nid = $node->id();
	foreach ($skillKeys as $key) {
      $data[$heroID][$nid][$key]['values'] = $node->get($key)->getValue();
	  foreach ($bonusNodes as $bNode) {
	    $skillID = $bNode->get('field_skill_reference')->getValue()['target_id'];
	    $nid = $bNode->id();
	    foreach ($bonusKeys as $bKey) {
	      $data[$heroID][$nid]['bonuses'][$bNid][$bKey]['values'] = $bNode->get($bKey)->getValue();
	    }
      }
	}
  }
  return $data;
}